### ISSUE TITLE
My pipeline completed but the extension wasn't uploaded

### ISSUE THREAD

**Issue by danhpham1510** [mnao305/chrome-extension-upload#5]
Hello, thank you for creating this action.

However, when I ran the action, it returned a few errors as listed below:
```
(node:2596) UnhandledPromiseRejectionWarning: HTTPError: Response code 400 (Bad Request)
    at /home/runner/work/_actions/mnao305/chrome-extension-upload/1.1.0/dist/index.js:4726:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
And the application wasn't updated on webstore. Do you happen to know the cause of this? Thank you!

**Comment by mnao305** [comment]
@danhpham1510 
Hello. Thank you open the Issue.

The error is probably due to one of the following:

- Review required to publish
- There is an error such as no explanation.

When I look at the webstore, these are displayed as "reasons why I can't publish", and I'm getting an error because I can't publish immediately.
If you think the cause is other than that, please send me a message again.

In addition, there was an inappropriate part of the error handling of this program, so I would like to correct it later.

I'm using Google Translate.

**Comment by mnao305** [comment]
Close.
If you still have problems, open the issue again.
